[platformio]
src_dir = platform
default_envs = esp32_rx

; -------------------------
; 1. Teensy 受信側
; -------------------------
[env:teensy_rx]
platform = teensy
board = teensy41 ; ※使用するTeensyのモデル(teensy40等)に合わせて変更
framework = arduino
monitor_speed = 115200
build_src_filter = +<teensy_rx/> -<esp32_rx/> -<esp32_tx/>

; -------------------------
; 2. ESP32 受信側
; -------------------------
[env:esp32_rx]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_port = /dev/ttyUSB0
monitor_port = /dev/ttyUSB0
build_flags =
    -I include/esp32_rx
    -I include/esp32_rx/can_comm
    -I include/esp32_rx/chassis_ctrl
    -I include/esp32_rx/i2c
    -I include/esp32_rx/im920_comm
    -I include/esp32_rx/laser_sensor
    -I include/esp32_rx/relay
    -I include/esp32_rx/servo_ctrl
    -I include/esp32_rx/util
lib_deps =
    adafruit/Adafruit PWM Servo Driver Library @ ^3.0.3
    adafruit/Adafruit_VL53L0X
build_src_filter = +<esp32_rx/> -<teensy_rx/> -<esp32_tx/>

; -------------------------
; 3. ESP32 送信側 (テスト・妨害用)
; -------------------------
[env:esp32_tx]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_src_filter = +<esp32_tx/> -<teensy_rx/> -<esp32_rx/>
