BCM: int
HIGH: int
IN: int
LOW: int
OUT: int

def cleanup() -> None: ...
def input(channel: int) -> int: ...
def output(channel: int, value: int) -> None: ...
def setmode(mode: int) -> None: ...
def setup(channel: int, mode: int) -> None: ...
def setwarnings(flag: bool) -> None: ...
